### ISSUE TITLE
Appdaemon complains wrong parameter type during "call_service" after upgrade from 0.16.7 to latest release today

### ISSUE THREAD

**Issue by bachmarc** [hassio-addons/addon-appdaemon#391]
HI, 
here is a small example code that executes fine under 0.16.7  but fails after add-on upgrade today.
If I revert to 0.16.7 (no backup no mercy) it again works fine.

I am calling alexa media player and feed it with tts text and a target. Target was always an array of entity names. 

````
import appdaemon.plugins.hass.hassapi as hass
class Tester(hass.Hass):
  def initialize(self):
    #define a data dict to enforce notification bell sound
    self.alexa_service_data = {
            "type": "announce",
            "method": "speak"}
    #define an array with two alexas
    self.my_target =["media_player.buro", "media_player.cassian"]  
    #call the service similar to what the developer tools do:
    self.call_service("notify/alexa_media", message='Test', target= self.my_target , data = self.alexa_service_data)      
````

In the log I see:

````
WARNING HASS: Error with websocket result: invalid_format: expected a dictionary for dictionary value @ data['target']. Got ['media_player.buro', 'media_player.cassian']
````

This is odd as the HA developer tools confirm that target has type Array and executes even after upgrade of appdaemon just normal. 
I played around now for 2 hours to get this fixed but failed. 
Tried a dict as demanded ant this causes only errors in direction of "extra keys not allowed" or "got String"...

Here the yaml of the developer tools that does the magic... only Appdaemon fails after upgrade 

````
action: notify.alexa_media
data:
  message: Das ist ein Test, hört ihr das?
  target:
    - media_player.buro
    - media_player.cassian
  data:
    type: announce
    method: speak
````
