### ISSUE TITLE
Thanks for the update, but still does not work with DialogFlow (not sure if this is issue with Addon, AppDaemon or config)

### ISSUE THREAD

**Issue by bruxy70** [hassio-addons/addon-appdaemon#43]
# Problem/Motivation

AppDaemon 4.0 finally supports SSL, so I am finally upgrading from 3.0. The Dialogflow still does not work though.

## Expected behavior

The Dialogflow calls AppDaemon on https://<host>:5050/api/appdaemon/dialogflow. The dialogflow app should respond. It works on 3.0

## Actual behavior

Dialog flow says the application is not responding. The error log shows:
```
2020-08-23 00:40:02.444927 INFO AppDaemon: App initialization complete
/usr/lib/python3.8/site-packages/appdaemon/__main__.py:133: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
  pending = asyncio.Task.all_tasks()
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._context.run(self._callback, *self._args)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._context.run(self._callback, *self._args)
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)
Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 275, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method
```

## Steps to reproduce

AppDaemon configuration
```YAML
appdaemon:
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 393
  time_zone: Europe/Prague
  api_port: 5050
  api_ssl_certificate: /ssl/fullchain.pem
  api_ssl_key: /ssl/privkey.pem
  api_key: !secret api
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      token: !secret token
api:
http:
  url: !secret url_appdaemon
```

## Proposed changes

I have no workaround, it works fine on 3.0. I have changed the appdaemon.yaml file according to the (confusing) documentation.
